// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(StockMarketDbContext))]
    [Migration("20260712163207_BuyOrder_SellOrder_TypesAlteration")]
    partial class BuyOrder_SellOrder_TypesAlteration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.BuyOrder", b =>
                {
                    b.Property<Guid>("BuyOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateAndTimeOfOrder")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("StockName");

                    b.Property<string>("StockSymbol")
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("StockSymbol");

                    b.HasKey("BuyOrderID");

                    b.ToTable("BuyOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_BuyOrders_Price", "[Price] >= 1 AND [Price] <= 100000");

                            t.HasCheckConstraint("CK_BuyOrders_Quantity", "[Quantity] >= 1 AND [Quantity] <= 100000");
                        });
                });

            modelBuilder.Entity("Entities.SellOrder", b =>
                {
                    b.Property<Guid>("SellOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateAndTimeOfOrder")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("StockName");

                    b.Property<string>("StockSymbol")
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("StockSymbol");

                    b.HasKey("SellOrderID");

                    b.ToTable("SellOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_SellOrders_Price", "[Price] >= 1 AND [Price] <= 100000");

                            t.HasCheckConstraint("CK_SellOrders_Quantity", "[Quantity] >= 1 AND [Quantity] <= 100000");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
